#!/usr/bin/env python3
"""gen_word_outline.py — regenerate word_outline.ae (real-typeface writing for
the tumbling cube).

Extracts the glyph OUTLINES for the word from a real font (DejaVu Sans Bold),
flattens the bézier contours to short line segments, lays the glyphs out on
the cube's front face ([-1,1]² face-local coords, y down), and emits an Aether
module whose word_path(ax, ay) projects every outline point through the same
rotate+perspective pipeline as the cube geometry and returns one compound SVG
path "d" string. Counters (the holes in A/e) come out as separate subpaths
with opposite winding — the backend's nonzero fill rule cuts them for free.

The projection constants MUST match tumbling_cube.ae (MIDX/MIDY/SC/DIST).

DejaVu Sans is distributed under the Bitstream Vera license (with public
domain extensions) — free to embed derived outline data with attribution.

Usage: python3 gen_word_outline.py   (writes word_outline.ae beside itself)
"""

import os
from fontTools.ttLib import TTFont
from fontTools.pens.basePen import BasePen

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
WORD = "AeVG"
FACE_WIDTH = 1.76          # target width in face-local units (face is 2.0 wide)
QUAD_STEPS = 4             # flatten steps per quadratic segment
CUBIC_STEPS = 6            # flatten steps per cubic segment

# Projection constants — keep in lockstep with tumbling_cube.ae.
MIDX, MIDY, SC, DIST = 210.0, 210.0, 170.0, 3.0


class FlattenPen(BasePen):
    """Records contours as flat point lists. BasePen decomposes TrueType
    qCurveTo runs into single quadratics for us (_qCurveToOne)."""

    def __init__(self, glyphSet, offset_x):
        super().__init__(glyphSet)
        self.offset_x = offset_x
        self.contours = []          # list of list[(x, y)] in font units
        self.cur = None

    def _pt(self, pt):
        return (pt[0] + self.offset_x, pt[1])

    def _moveTo(self, pt):
        self.cur = [self._pt(pt)]

    def _lineTo(self, pt):
        self.cur.append(self._pt(pt))

    def _qCurveToOne(self, pt1, pt2):
        x0, y0 = self.cur[-1][0] - self.offset_x, self.cur[-1][1]
        for i in range(1, QUAD_STEPS + 1):
            t = i / QUAD_STEPS
            mt = 1 - t
            x = mt * mt * x0 + 2 * mt * t * pt1[0] + t * t * pt2[0]
            y = mt * mt * y0 + 2 * mt * t * pt1[1] + t * t * pt2[1]
            self.cur.append(self._pt((x, y)))

    def _curveToOne(self, pt1, pt2, pt3):
        x0, y0 = self.cur[-1][0] - self.offset_x, self.cur[-1][1]
        for i in range(1, CUBIC_STEPS + 1):
            t = i / CUBIC_STEPS
            mt = 1 - t
            x = (mt**3 * x0 + 3 * mt * mt * t * pt1[0]
                 + 3 * mt * t * t * pt2[0] + t**3 * pt3[0])
            y = (mt**3 * y0 + 3 * mt * mt * t * pt1[1]
                 + 3 * mt * t * t * pt2[1] + t**3 * pt3[1])
            self.cur.append(self._pt((x, y)))

    def _closePath(self):
        self.contours.append(self.cur)
        self.cur = None


def main():
    font = TTFont(FONT)
    glyphset = font.getGlyphSet()
    cmap = font.getBestCmap()

    contours = []
    pen_x = 0.0
    for ch in WORD:
        gname = cmap[ord(ch)]
        pen = FlattenPen(glyphset, pen_x)
        glyphset[gname].draw(pen)
        contours.extend(pen.contours)
        pen_x += glyphset[gname].width

    # Normalize: word centred at origin, FACE_WIDTH wide, y flipped (font is
    # y-up, the face is y-down), vertically centred on the cap-height band.
    xs = [x for c in contours for x, _ in c]
    ys = [y for c in contours for _, y in c]
    minx, maxx = min(xs), max(xs)
    miny, maxy = min(ys), max(ys)
    s = FACE_WIDTH / (maxx - minx)
    cx = (minx + maxx) / 2.0
    cy = (miny + maxy) / 2.0
    norm = [[((x - cx) * s, -(y - cy) * s) for x, y in c] for c in contours]

    npts = sum(len(c) for c in norm)
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "word_outline.ae")
    with open(out, "w") as f:
        f.write(f'''// word_outline.ae — GENERATED by gen_word_outline.py. Do not hand-edit.
//
// The word "{WORD}" as real-typeface outlines: {len(norm)} contours /
// {npts} points from DejaVu Sans Bold (Bitstream Vera license), flattened
// and normalized to the cube's front-face coords ([-1,1]², y down).
// word_path(ax, ay) perspective-projects every point (same pipeline as the
// cube: rotate Y then X, f = SC/(DIST-z), z=+1 plane) and returns ONE
// compound SVG path — counters keep opposite winding, so the backend's
// nonzero fill rule renders the holes.
//
// Projection constants mirror tumbling_cube.ae — regenerate if they change.

exports (word_path)

import std.math
import std.string

extern lrint(x: float) -> long

W_MIDX() -> float {{ return {MIDX} }}
W_MIDY() -> float {{ return {MIDY} }}
W_SC()   -> float {{ return {SC} }}
W_DIST() -> float {{ return {DIST} }}

// Project face-local (u, v) on the z=+1 plane → "<cmd> x y" (1-decimal).
wp(ax: float, ay: float, cmd: string, u: float, v: float) -> string {{
    x1 = u * math.cos(ay) + math.sin(ay)
    z1 = math.cos(ay) - u * math.sin(ay)
    y1 = v * math.cos(ax) + z1 * math.sin(ax)
    z2 = z1 * math.cos(ax) - v * math.sin(ax)
    f = W_SC() / (W_DIST() - z2)
    a = string.concat(cmd, " ")
    a = string.concat(a, f1(W_MIDX() + x1 * f))
    a = string.concat(a, " ")
    return string.concat(a, f1(W_MIDY() + y1 * f))
}}

// One-decimal float → string ("123.4").
f1(v: float) -> string {{
    n = lrint(v * 10.0) as int
    whole = n / 10
    frac = n % 10
    if frac < 0 {{ frac = 0 - frac }}
    if n < 0 && whole == 0 {{
        return string.concat("-0.", string.from_int(frac))
    }}
    return string.concat(string.concat(string.from_int(whole), "."),
                         string.from_int(frac))
}}

''')
        f.write("word_path(ax: float, ay: float) -> string {\n")
        f.write('    s = ""\n')
        for c in norm:
            for j, (u, v) in enumerate(c):
                cmd = "M" if j == 0 else " L"
                f.write(f'    s = string.concat(s, wp(ax, ay, "{cmd}", {u:.4f}, {v:.4f}))\n')
            f.write('    s = string.concat(s, " Z ")\n')
        f.write("    return s\n}\n")
    print(f"wrote {out}: {len(norm)} contours, {npts} points")


if __name__ == "__main__":
    main()
